//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.20 at 05:37:15 PM CDT 
//


package org.example.employee;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for getEmployeeResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getEmployeeResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eligibilityCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="eligibilityMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getEmployeeResponse", propOrder = {
    "eligibilityCode",
    "eligibilityMessage"
})
public class GetEmployeeResponse {

    protected int eligibilityCode;
    @XmlElement(required = true)
    protected String eligibilityMessage;

    /**
     * Gets the value of the eligibilityCode property.
     * 
     */
    public int getEligibilityCode() {
        return eligibilityCode;
    }

    /**
     * Sets the value of the eligibilityCode property.
     * 
     */
    public void setEligibilityCode(int value) {
        this.eligibilityCode = value;
    }

    /**
     * Gets the value of the eligibilityMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEligibilityMessage() {
        return eligibilityMessage;
    }

    /**
     * Sets the value of the eligibilityMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEligibilityMessage(String value) {
        this.eligibilityMessage = value;
    }

}
