//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.20 at 05:37:15 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/Employee", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.example.employee;
